# Site settings
title: Arctic Fox
email: 
description: > # this means to ignore newlines until "baseurl:"
  Jekyll Theme Demo

twitter_username: username
github_username: username

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
